Result lecture 4
AlexLex13/phoneshop-servlet-api pull request #5
Opened 2023-05-23 09:24 UTC by AlexLex13

2023-05-25 10:51 UTC, YauheniBylkou requested changes

2023-05-25 10:51 UTC, YauheniBylkou commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +    }
see the duplication of that method in another servlet, i suggest to create AbstractServlet and place thislogic here. Also, AbstractServlet can contain some other duplicate logic or dependencies, for ex. cartService

2023-05-25 10:51 UTC, YauheniBylkou commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +
what is it responsible for?

2023-05-25 10:51 UTC, YauheniBylkou commented on src/main/webapp/WEB-INF/pages/productList.jsp
>    </form>
it would be great to have a success or error message here after adding to cart from plp

2023-05-25 10:51 UTC, YauheniBylkou commented on src/main/webapp/WEB-INF/pages/minicart.jsp
> + | <a class="miniCart" href="${pageContext.servletContext.contextPath}/cart">Cart</a>: ${cart.totalQuantity}
dissappears after wrong update on cart page

2023-05-25 22:15 UTC, AlexLex13 commented on src/main/webapp/WEB-INF/pages/minicart.jsp
> + | <a class="miniCart" href="${pageContext.servletContext.contextPath}/cart">Cart</a>: ${cart.totalQuantity}
This is due to the fact that if an error has occurred, then we call the doGet method in the body of the doPost method. Because of this, include is lost and I do not know why(

2023-05-26 14:59 UTC, YauheniBylkou commented on src/main/webapp/WEB-INF/pages/minicart.jsp
> + | <a class="miniCart" href="${pageContext.servletContext.contextPath}/cart">Cart</a>: ${cart.totalQuantity}
accepted

2023-05-26 15:00 UTC, YauheniBylkou approved these changes

2023-05-26 16:09 UTC, merged